# Generated by Django 5.1.2 on 2024-10-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='rollnumber',
            new_name='employeeid',
        ),
    ]
